$(()=>{
    $("#megaStart").on("click",()=>{
        $("#megamain").addClass("disapearing")
        window.setTimeout(()=>{
            $("body").load("second.html")
            window.setTimeout(()=>{
                $(".answ").css("animation-name","none")
            })
        },800)
    })
})