$(()=>{
    $("#megamain").one("animationend",()=>{
        console.log("xtraxtraxtra");
    })
    $("#megaStart").one("click",()=>{
        $("#megamain").addClass("vanishing");
        $("#megamain.vanishing").one("animationend",()=>{
            $("body").load("second.html");
        })
    })
})